<html>
<head>
	<title>Cinet Manual</title>
	<link rel="stylesheet" type="text/css" href="{{asset('cinetmanualassets/style.css')}}">
</head>
<body>
	<div class="content">
		<h1 class="header1">Table Of Content</h1>
		<ol>
			<li>Introduction</li>
		 <li>Summary of Procuring Agency's Task </li>
		 <li>Accessing CiNet</li>
		 <li>Dashboard</li>
		 <li>Upload Tender</li>
		 <li>List of Uploaded Tender</li>
		 <li>Bidding Form.....</li>
		 <li>Edit Bidding Form</li>
		 <li>Completion Form Report</li>
		</ol>
		<div>
			<h1 class="header1">1. Introduction</h1>
			<p class="para">The tenders can be uploaded online through the secure interface called the CiNET from where it will be advertised on the CDB website. CiNet is use to send the tenders that are to be published in the CDB website by the procuring agencies. Each identified focal person on the Procuring Agency side is provided with a login Name and Password which can be used to access into the CiNET section. <br><br>
			From here they will upload the Tender information. Furthermore they will also enter the bid report (Bidding Form) along with the evaluated bid detail and the bids that were not evaluated by the procuring agencies. This also reflects the information about who the tender was awarded to. Thereafter the procuring agency will also enter the contract completion report, i.e. the analysis of, how the contractor had performed on the job given to the party. The reports of the contactors’ work in hand, equipment detail, and HR can also be viewed by the procuring Agency to analyze.</p>
			<h1 class="header1">2.	Accessing CiNET</h1>
			<p class="para">In order to for the procuring agency to upload a tender the procuring agency first need to open the CDB web site by typing on the internet explorer the <a href="www.cdb.gov.bt">www.cdb.gov.bt</a> </p>
					<img src="{{asset('cinetmanualassets/Images/c1.jpg')}}" class="img"/>
					<p class="para">Here in this home page we can see the E-Zotin menu on the top corner of the web site. You can click on this dropdown menu, select CiNET.</p>
					<img src="{{asset('cinetmanualassets/Images/c2.jpg')}}" class="img"/>
				<h1 class="header1">Dashboard</h1>
					<img src="{{asset('cinetmanualassets/Images/c3.jpg')}}" class="img"/>
				<p class="para">This dashboard displays the latest Notice and News for Procuring Agency and also the 					menu for various interfaces is shown at the top menu of the page.</p>
				<h1 class="header1">Upload Tender</h1>
				<p class="para">This dashboard displays the latest Notice and News for Procuring Agency and also the 					menu for various interfaces is shown at the top menu of the page.</p>
					<img src="{{asset('cinetmanualassets/Images/c4.jpg')}}" class="img"/>
				<p>NOTE: Date and time selection is based on 24 hour format.</p>
				<p class="para">You can add as many tender you like by using the above page but it should be valid. Here you are provided with the relevant fields where you can add the information of a tender. This is the page from where you can upload new tender into the web page. You need to add the details in accordance to the boxes corresponding to their name on the left side. On the first box you can see the reference No. This reference No. will be entered by the concerned procuring agency. <br><br>
				The contract period will be in months. Tentative start date and tentative end date will depend on the contract period (for example: if the contract period is 12 month, you will select the tentative start date, tentative end date will be auto calculated, 12 months from the tentative start date) and the Dzongkhag list shows that it is the exact location for the work to be carried on. In the Filename box click the Choose Files button to locate the tender documents at your system that is to be uploaded in the CDB website. This particular tender uploaded by you will be reflected on the cdb website at the sidebar where tender reflects. Click on Cancel button to cancel the process.</p>
				<h1 class="header1">List of Uploaded Tender</h1>
						<img src="{{asset('cinetmanualassets/Images/c5.jpg')}}" class="img"/>
					<p class="para">List of uploaded tender will display the entire list of tenders that the particular procuring agencies have uploaded till date. Tender can be searched using work id, category and classification. Click on Search button to display the list and clear button to clear the filters.
						This work id is automatically generated by the system in the format Procuring Agency name, following with the current year and the serial number of tenders uploaded for that particular year. The work id number will restart form 1 after every one year. The work id cannot be edited or changed with a new one unless the procuring agency is changed. <br><br>
						<b>Edit</b><br>
						To edit the information of uploaded tender, click on the Edit button against each list and the following page will be displayed.
					</p>
						<img src="{{asset('cinetmanualassets/Images/c6.jpg')}}" class="img"/>
						<p class="para">You can edit the tender details in case of re-tender or to make necessary correction to the tender. In case where you need to re-tender the previously tendered work, you can always use this edit link to edit the information and re-tender. <br><br>
							To view the uploaded tender related document, click on the link below document name or you can delete the file by clicking on the delete link. <br><br>
							To replace the uploaded tender related document, you just have to upload the new document and the system will replace the old document with the new one. <br><br>
							The details of a particular work will be displayed here in their respective boxes. You can edit any of the information whichever you feel is relevant for changes. After you are done editing you just need to click on the ‘Save’ button. <br><br>
							<b>Delete</b> <br>
							To delete the information of uploaded tender, click on the Delete button and the following pop up page will be displayed.</p>
						<img src="{{asset('cinetmanualassets/Images/c7.jpg')}}" />
						<p>Enter the remarks and click on Delete button to delete the tender and Cancel button to cancel the process.<br>
						Note: After the closing date of sale of tender, the procuring agencies will not be able to edit or delete the tender.</p>
						<h1 class="header1">Bidding Form</h1>
						<img src="{{asset('cinetmanualassets/Images/c8.jpg')}}" class="img"/>
						<p>Bidding forms are filled after the work has been awarded.</p>
						<h1 class="header1">Edit Bidding Form</h1>
						<img src="{{asset('cinetmanualassets/Images/c9.jpg')}}" class="img"/>
						<p class="para"> The entire bidding form will be listed in the above page. Procuring agencies will select the particular bidding form by clicking the “Edit” button and the following page will be displayed</p>
						<img src="{{asset('cinetmanualassets/Images/c10.jpg')}}" class="img"/>
						<p>After making all the changes, click on “Save” button to save the information and “Cancel” button to cancel the process.</p>
						<h1 class="header1">Completion Report </h1>
						<p class="para">Here the list of the work that has been evaluated and the work that has been awarded to any one of the contractor will be displayed. This page has to correspond with the Evaluation page. Only after the work has been awarded to a contractor, the details will be listed here. This is the conclusion page whereby you need to enter the final scoring for that particular work. And once you enter the final score, it means the work has been “Completed” and the details will not be seen any more on this page.</p>
						<h1 class="header1">Report</h1>
						<p class="para">On clicking this button you will be able to view the entire report of all the contractors for a particular work. The following page opens up to you:
						Here you will know how many contractors have participated and can view full details how much a contractor scored. You will also be able to find out the Technical and Financial Score of a particular contractor as well as his preference score. You can also view the details of the Evaluation committee members.
						</p>
		</div>
	</div>
</body>
</html>